# permissions for end users to edit apiclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiclient-editor-role
rules:
- apiGroups:
  - platform.my.domain
  resources:
  - apiclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.my.domain
  resources:
  - apiclients/status
  verbs:
  - get
