# permissions for end users to edit apigateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apigateway-editor-role
rules:
- apiGroups:
  - platform.my.domain
  resources:
  - apigateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.my.domain
  resources:
  - apigateways/status
  verbs:
  - get
