# permissions for end users to view apigateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apigateway-viewer-role
rules:
- apiGroups:
  - platform.my.domain
  resources:
  - apigateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.my.domain
  resources:
  - apigateways/status
  verbs:
  - get
