
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - platform.my.domain
  resources:
  - apiclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.my.domain
  resources:
  - apiclients/finalizers
  verbs:
  - update
- apiGroups:
  - platform.my.domain
  resources:
  - apiclients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - platform.my.domain
  resources:
  - apigateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.my.domain
  resources:
  - apigateways/finalizers
  verbs:
  - update
- apiGroups:
  - platform.my.domain
  resources:
  - apigateways/status
  verbs:
  - get
  - patch
  - update
